[ODPR-1424] - SUB-16.Add processingDate
hmrc/digital-platform-reporting pull request #23
Opened 2024-09-04 14:34 UTC by Rabina-Rai

- Adds 'processingDate' which we get back in the response already. This is to be used in the frontend for [ODPR-1424](https://jira.tools.tax.service.gov.uk/browse/ODPR-1424)
- renamed "SubscribedResponseSpec" -> "SubscriptionResponseSpec" as the file name and class name were different and the compiler threw up a warning about it

2024-09-04 16:55 UTC, georgievh requested changes

2024-09-04 16:55 UTC, georgievh commented on app/models/subscription/responses/SubscriptionResponse.scala
> +  implicit lazy val reads: Reads[SubscribedResponse] = (
It is good if you test this serialization.

2024-09-05 15:02 UTC, georgievh approved these changes

2024-09-05 15:09 UTC, paddynski-opencast approved these changes

2024-09-06 15:54 UTC, merged